---
- name: Clone
  hosts: app
  become: yes
  tasks:
    - name: Install git
      apt: 
        name: git
        state: present
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
